"""initial_schema"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

revision = "001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.create_table("organizations", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("name", sa.Text(), nullable=False), sa.Column("plan_type", sa.Text(), nullable=False), sa.Column("owner_email", sa.Text(), nullable=False), sa.Column("telegram_chat_id", sa.Text()), sa.Column("resend_from_email", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("projects", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("org_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("name", sa.Text(), nullable=False), sa.Column("slug", sa.Text(), nullable=False), sa.Column("business_model", sa.Text(), nullable=False), sa.Column("status", sa.Text(), nullable=False), sa.Column("primary_goal", sa.Text(), nullable=False), sa.Column("website_url", sa.Text()), sa.Column("priority", sa.Integer(), nullable=False), sa.Column("channels", postgresql.JSONB(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("slug"))
    op.create_table("project_memory", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("project_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("icp", postgresql.JSONB(), nullable=False), sa.Column("positioning", sa.Text()), sa.Column("offers", postgresql.JSONB(), nullable=False), sa.Column("tone", sa.Text()), sa.Column("languages", postgresql.ARRAY(sa.Text()), nullable=False), sa.Column("funnel_goals", postgresql.JSONB(), nullable=False), sa.Column("constraints", postgresql.JSONB(), nullable=False), sa.Column("approved_examples", postgresql.JSONB(), nullable=False), sa.Column("rejected_examples", postgresql.JSONB(), nullable=False), sa.Column("performance_learnings", sa.Text()), sa.Column("version", sa.Integer(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("project_id"))
    op.create_table("brand_memory", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("project_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("logo_url", sa.Text()), sa.Column("color_palette", postgresql.JSONB(), nullable=False), sa.Column("typography", postgresql.JSONB(), nullable=False), sa.Column("arabic_font_url", sa.Text()), sa.Column("visual_style", sa.Text()), sa.Column("image_style", sa.Text()), sa.Column("brand_voice", sa.Text()), sa.Column("dos", postgresql.JSONB(), nullable=False), sa.Column("donts", postgresql.JSONB(), nullable=False), sa.Column("templates", postgresql.JSONB(), nullable=False), sa.Column("rejected_styles", postgresql.JSONB(), nullable=False), sa.Column("is_provisional", sa.Boolean(), nullable=False), sa.Column("approved_at", sa.DateTime(timezone=True)), sa.Column("version", sa.Integer(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("project_id"))
    op.create_table("weekly_plans", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("project_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("week_start", sa.Date(), nullable=False), sa.Column("objective", sa.Text(), nullable=False), sa.Column("funnel_focus", sa.Text(), nullable=False), sa.Column("tactics", postgresql.JSONB(), nullable=False), sa.Column("total_budget_estimate", sa.Numeric(10, 2), nullable=False), sa.Column("rationale", sa.Text(), nullable=False), sa.Column("risk_flags", postgresql.JSONB(), nullable=False), sa.Column("status", sa.Text(), nullable=False), sa.Column("approval_id", postgresql.UUID(as_uuid=True)), sa.Column("created_by", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("assets", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("project_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("weekly_plan_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("weekly_plans.id")), sa.Column("tactic_id", sa.Text()), sa.Column("type", sa.Text(), nullable=False), sa.Column("channel", sa.Text(), nullable=False), sa.Column("language", sa.Text(), nullable=False), sa.Column("copy_ar", sa.Text()), sa.Column("copy_en", sa.Text()), sa.Column("copy_bilingual", postgresql.JSONB()), sa.Column("design_prompt", sa.Text()), sa.Column("design_url", sa.Text()), sa.Column("design_thumbnail_url", sa.Text()), sa.Column("platform_dimensions", postgresql.JSONB()), sa.Column("status", sa.Text(), nullable=False), sa.Column("qa_score", sa.Numeric(5, 2)), sa.Column("qa_passed", sa.Boolean()), sa.Column("qa_notes", postgresql.JSONB(), nullable=False), sa.Column("rejection_reason", sa.Text()), sa.Column("edit_instructions", sa.Text()), sa.Column("platform_post_id", sa.Text()), sa.Column("variants", postgresql.JSONB(), nullable=False), sa.Column("embedding", Vector(1536)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("approvals", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("asset_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("assets.id")), sa.Column("weekly_plan_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("weekly_plans.id")), sa.Column("approver_id", sa.Text(), nullable=False), sa.Column("decision", sa.Text()), sa.Column("reason", sa.Text()), sa.Column("edit_instructions", sa.Text()), sa.Column("notification_channels", postgresql.ARRAY(sa.Text()), nullable=False), sa.Column("notification_sent_at", sa.DateTime(timezone=True)), sa.Column("decided_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("publish_jobs", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("asset_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("assets.id", ondelete="CASCADE"), nullable=False), sa.Column("approval_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("approvals.id"), nullable=False), sa.Column("channel", sa.Text(), nullable=False), sa.Column("channel_account_id", sa.Text()), sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False), sa.Column("published_at", sa.DateTime(timezone=True)), sa.Column("platform_post_id", sa.Text()), sa.Column("status", sa.Text(), nullable=False), sa.Column("error_message", sa.Text()), sa.Column("retry_count", sa.Integer(), nullable=False), sa.Column("max_retries", sa.Integer(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("metric_snapshots", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("project_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("asset_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("assets.id")), sa.Column("channel", sa.Text(), nullable=False), sa.Column("metric_type", sa.Text(), nullable=False), sa.Column("value", sa.Numeric(15, 4), nullable=False), sa.Column("date", sa.Date(), nullable=False), sa.Column("source", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("audit_events", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("actor_type", sa.Text(), nullable=False), sa.Column("actor_id", sa.Text(), nullable=False), sa.Column("action", sa.Text(), nullable=False), sa.Column("object_type", sa.Text(), nullable=False), sa.Column("object_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("metadata", postgresql.JSONB(), nullable=False), sa.Column("ip_address", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))

def downgrade() -> None:
    pass
